Repository googleapis/python-memcache, pull requests merged in 2021-09, with the labels that each got.

#100 chore: revert owlbot main branch templates
  owlbot.py
Labels: automerge, kokoro:force-run, cla: yes, api: memcache

#101 chore: reference main branch of google-cloud-python
  README.rst
Labels: cla: yes, api: memcache

#103 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: automerge, cla: yes, api: memcache
