Repository googleapis/python-memcache, pull requests merged in 2021-04, with the labels that each got.

#43 chore: start tracking obsolete files
  synth.metadata
Labels: api: memcache, cla: yes, context: full

#45 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: memcache, automerge, cla: yes, context: full

#44 chore: add tarfile
  memcache-v1beta2-py.tar.gz
  synth.metadata
Labels: api: memcache, automerge, cla: yes, context: none

#48 chore: prevent normalization of semver versioning
  setup.py
Labels: api: memcache, cla: yes

#49 chore(revert): revert preventing normalization
  setup.py
Labels: api: memcache, cla: yes
