Repository googleapis/python-memcache, pull requests merged in 2022-06, with the labels that each got.

#184 fix(deps): require protobuf <4.0.0dev
  setup.py
  testing/constraints-3.6.txt
Labels: api: memcache, size: xs

#183 docs: fix changelog header to consistent size
  CHANGELOG.md
Labels: api: memcache, size: s

#187 chore: test minimum dependencies in python 3.7
  testing/constraints-3.7.txt
Labels: api: memcache, size: s

#188 fix(deps): require protobuf<4.0.0 on v0 branch
  noxfile.py
  setup.py
Labels: api: memcache, size: xs

#195 fix: exclude tests directory in packaging
  setup.py
Labels: api: memcache, size: m
